swagger: '2.0'
info:
  title: Rust API Gateway
  description: API Gateway built with Rust
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      x-google-backend:
        address: https://db-endpoint-l3l4na2aua-uc.a.run.app/health
        protocol: h2
      responses:
        '200':
          description: Service is healthy
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
  /api/{path+}:
    get:
      summary: Proxy GET requests
      operationId: proxyGet
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: service
          in: query
          type: string
      x-google-backend:
        address: https://db-endpoint-l3l4na2aua-uc.a.run.app/api/{path}
        protocol: h2
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '503':
          description: Service unavailable
    post:
      summary: Proxy POST requests
      operationId: proxyPost
      parameters:
        - name: path
          in: path
          required: true
          type: string
        - name: service
          in: query
          type: string
        - name: body
          in: body
          schema:
            type: object
      x-google-backend:
        address: https://db-endpoint-l3l4na2aua-uc.a.run.app/api/{path}
        protocol: h2
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '503':
          description: Service unavailable
