apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: db-endpoint
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containerConcurrency: 100
      containers:
      - image: gcr.io/PROJECT_ID/db-endpoint:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: AUTH_SERVICE_URL
          value: "https://auth-service-url"
        - name: USERS_SERVICE_URL
          value: "https://users-service-url"
        - name: RUST_LOG
          value: "info"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi